# Generated by Django 5.2.4 on 2025-07-27 16:35

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_slip',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='payment_slip'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('AWAITING_PAYMENT', 'Awaiting Payment'), ('PREPARING', 'Preparing'), ('DELIVERING', 'Out for Delivery'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='AWAITING_PAYMENT', max_length=20),
        ),
    ]
