# Generated by Django 5.2.4 on 2026-01-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_order_payment_slip_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('AWAITING_PAYMENT', 'Awaiting Payment'), ('PREPARING', 'Preparing'), ('DELIVERING', 'Out for Delivery'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
