# Generated by Django 5.2.4 on 2026-03-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_orderitem_menu_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_telegram_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
