# Generated by Django 5.2.4 on 2026-03-20 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_order_customer_telegram_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_telegram_id',
            new_name='customer_telegram_chat_id',
        ),
    ]
